### ISSUE TITLE
Race condition on MacOS

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#1030]
**Describe the bug**

Running the visor on macOS with the `-race` throws a race condition 

```
sudo ./skywire-visor -c ./visor-vpn-client.json
skywire-visor(45639,0x147a0600) malloc: *** error for object 0x600001700080: pointer being freed was not allocated
skywire-visor(45639,0x147a0600) malloc: *** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7ff816994112 m=0 sigcode=0

goroutine 0 [idle]:
syscall.rawSyscall(0x40929e0, 0x0, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/runtime/sys_darwin.go:77 +0x47 fp=0xc00017f178 sp=0xc00017f158 pc=0x406be47
syscall.rawSyscall(0x4071fc5, 0x0, 0x0, 0x1)
        <autogenerated>:1 +0x26 fp=0xc00017f1c0 sp=0xc00017f178 pc=0x40729c6
syscall.forkAndExecInChild(0xc0002a0d38, {0xc00029a2c0, 0x7, 0x1}, {0xc0002af0e0, 0x13, 0x0}, 0x0, 0x0, 0xc00017f4c8, ...)
        /usr/local/opt/go/libexec/src/syscall/exec_libc2.go:80 +0xed fp=0xc00017f250 sp=0xc00017f1c0 pc=0x4086d8d
syscall.forkExec({0xc0002a0cf9, 0x7}, {0xc00028e4e0, 0x6, 0x6}, 0xc00017f4c8)
        /usr/local/opt/go/libexec/src/syscall/exec_unix.go:210 +0x58f fp=0xc00017f3e8 sp=0xc00017f250 pc=0x4087e0f
syscall.StartProcess(...)
        /usr/local/opt/go/libexec/src/syscall/exec_unix.go:256
os.startProcess({0xc0002a0cf9, 0x7}, {0xc00028e4e0, 0x6, 0x6}, 0xc00017f758)
        /usr/local/opt/go/libexec/src/os/exec_posix.go:55 +0x526 fp=0xc00017f520 sp=0xc00017f3e8 pc=0x40cd986
os.StartProcess({0xc0002a0cf9, 0x7}, {0xc00028e4e0, 0x6, 0x6}, 0x2)
        /usr/local/opt/go/libexec/src/os/exec.go:109 +0x7a fp=0xc00017f580 sp=0xc00017f520 pc=0x40cce1a
os/exec.(*Cmd).Start(0xc0002d42c0)
        /usr/local/opt/go/libexec/src/os/exec/exec.go:422 +0x9d4 fp=0xc00017f7b0 sp=0xc00017f580 pc=0x4636174
github.com/shirou/gopsutil/v3/internal/common.Invoke.CommandWithContext({}, {0x5487c90, 0xc0000360d8}, {0xc0002a0cf9, 0x7}, {0xc0002a64b0, 0x5, 0x5})
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/internal/common/common.go:53 +0x1cc fp=0xc00017f838 sp=0xc00017f7b0 pc=0x463f3ec
github.com/shirou/gopsutil/v3/internal/common.(*Invoke).CommandWithContext(0x65c7960, {0x5487c90, 0xc0000360d8}, {0xc0002a0cf9, 0x7}, {0xc0002a64b0, 0x5, 0x5})
        <autogenerated>:1 +0xaf fp=0xc00017f8a8 sp=0xc00017f838 pc=0x463fc4f
github.com/shirou/gopsutil/v3/process.callPsWithContext({0x5487c90, 0xc0000360d8}, {0x4d5f25d, 0x5}, 0xb1ec, 0x0, 0x0)
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process_darwin.go:450 +0x698 fp=0xc00017fa08 sp=0xc00017f8a8 pc=0x4646f18
github.com/shirou/gopsutil/v3/process.(*Process).createTimeWithContext(0xc0002a4820, {0x5487c90, 0xc0000360d8})
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process_darwin.go:127 +0x8b fp=0xc00017faf0 sp=0xc00017fa08 pc=0x464646b
github.com/shirou/gopsutil/v3/process.(*Process).CreateTimeWithContext(0xc0002a4820, {0x5487c90, 0xc0000360d8})
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process.go:287 +0x9d fp=0xc00017fb40 sp=0xc00017faf0 pc=0x46461bd
github.com/shirou/gopsutil/v3/process.NewProcessWithContext({0x5487c90, 0xc0000360d8}, 0xb1ec)
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process.go:195 +0x125 fp=0xc00017fba0 sp=0xc00017fb40 pc=0x4646065
github.com/shirou/gopsutil/v3/process.NewProcess(...)
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process.go:179
github.com/skycoin/skywire/pkg/restart.ppidByPid(0xb1ec)
        /Users/alex/workspace/skycoin/skywire/pkg/restart/restart.go:228 +0x4c fp=0xc00017fbd8 sp=0xc00017fba0 pc=0x464968c
github.com/skycoin/skywire/pkg/restart.CaptureContext()
        /Users/alex/workspace/skycoin/skywire/pkg/restart/restart.go:68 +0x36f fp=0xc00017fcd8 sp=0xc00017fbd8 pc=0x4647f0f
        /usr/local/opt/go/libexec/src/syscall/exec_unix.go:256                                                                                                                                                   [425/4229]
os.startProcess({0xc0002a0cf9, 0x7}, {0xc00028e4e0, 0x6, 0x6}, 0xc00017f758)
        /usr/local/opt/go/libexec/src/os/exec_posix.go:55 +0x526 fp=0xc00017f520 sp=0xc00017f3e8 pc=0x40cd986
os.StartProcess({0xc0002a0cf9, 0x7}, {0xc00028e4e0, 0x6, 0x6}, 0x2)
        /usr/local/opt/go/libexec/src/os/exec.go:109 +0x7a fp=0xc00017f580 sp=0xc00017f520 pc=0x40cce1a
os/exec.(*Cmd).Start(0xc0002d42c0)
        /usr/local/opt/go/libexec/src/os/exec/exec.go:422 +0x9d4 fp=0xc00017f7b0 sp=0xc00017f580 pc=0x4636174
github.com/shirou/gopsutil/v3/internal/common.Invoke.CommandWithContext({}, {0x5487c90, 0xc0000360d8}, {0xc0002a0cf9, 0x7}, {0xc0002a64b0, 0x5, 0x5})
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/internal/common/common.go:53 +0x1cc fp=0xc00017f838 sp=0xc00017f7b0 pc=0x463f3ec
github.com/shirou/gopsutil/v3/internal/common.(*Invoke).CommandWithContext(0x65c7960, {0x5487c90, 0xc0000360d8}, {0xc0002a0cf9, 0x7}, {0xc0002a64b0, 0x5, 0x5})
        <autogenerated>:1 +0xaf fp=0xc00017f8a8 sp=0xc00017f838 pc=0x463fc4f
github.com/shirou/gopsutil/v3/process.callPsWithContext({0x5487c90, 0xc0000360d8}, {0x4d5f25d, 0x5}, 0xb1ec, 0x0, 0x0)
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process_darwin.go:450 +0x698 fp=0xc00017fa08 sp=0xc00017f8a8 pc=0x4646f18
github.com/shirou/gopsutil/v3/process.(*Process).createTimeWithContext(0xc0002a4820, {0x5487c90, 0xc0000360d8})
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process_darwin.go:127 +0x8b fp=0xc00017faf0 sp=0xc00017fa08 pc=0x464646b
github.com/shirou/gopsutil/v3/process.(*Process).CreateTimeWithContext(0xc0002a4820, {0x5487c90, 0xc0000360d8})
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process.go:287 +0x9d fp=0xc00017fb40 sp=0xc00017faf0 pc=0x46461bd
github.com/shirou/gopsutil/v3/process.NewProcessWithContext({0x5487c90, 0xc0000360d8}, 0xb1ec)
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process.go:195 +0x125 fp=0xc00017fba0 sp=0xc00017fb40 pc=0x4646065
github.com/shirou/gopsutil/v3/process.NewProcess(...)
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process.go:179
github.com/skycoin/skywire/pkg/restart.ppidByPid(0xb1ec)
        /Users/alex/workspace/skycoin/skywire/pkg/restart/restart.go:228 +0x4c fp=0xc00017fbd8 sp=0xc00017fba0 pc=0x464968c
github.com/skycoin/skywire/pkg/restart.CaptureContext()
        /Users/alex/workspace/skycoin/skywire/pkg/restart/restart.go:68 +0x36f fp=0xc00017fcd8 sp=0xc00017fbd8 pc=0x4647f0f
github.com/skycoin/skywire/cmd/skywire-visor/commands.init()
        /Users/alex/workspace/skycoin/skywire/cmd/skywire-visor/commands/root.go:36 +0x72 fp=0xc00017fd10 sp=0xc00017fcd8 pc=0x4ba3f32
runtime.doInit(0x59e08a0)
        /usr/local/opt/go/libexec/src/runtime/proc.go:6498 +0x123 fp=0xc00017fe48 sp=0xc00017fd10 pc=0x4049663
runtime.doInit(0x59d34c0)
        /usr/local/opt/go/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc00017ff80 sp=0xc00017fe48 pc=0x40495b1
runtime.main()
        /usr/local/opt/go/libexec/src/runtime/proc.go:238 +0x1e6 fp=0xc00017ffe0 sp=0xc00017ff80 pc=0x403bf86
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00017ffe8 sp=0xc00017ffe0 pc=0x406f2a1

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:350 fp=0xc00017f128 sp=0xc00017f120 pc=0x406d060
runtime.libcCall(0x18, 0x5b75720)
        /usr/local/opt/go/libexec/src/runtime/sys_libc.go:49 +0x66 fp=0xc00017f158 sp=0xc00017f128 pc=0x405aea6
syscall.rawSyscall(0x40929e0, 0x0, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/runtime/sys_darwin.go:77 +0x47 fp=0xc00017f178 sp=0xc00017f158 pc=0x406be47
syscall.rawSyscall(0x4071fc5, 0x0, 0x0, 0x1)
        <autogenerated>:1 +0x26 fp=0xc00017f1c0 sp=0xc00017f178 pc=0x40729c6
syscall.forkAndExecInChild(0xc0002a0d38, {0xc00029a2c0, 0x7, 0x1}, {0xc0002af0e0, 0x13, 0x0}, 0x0, 0x0, 0xc00017f4c8, ...)
        /usr/local/opt/go/libexec/src/syscall/exec_libc2.go:80 +0xed fp=0xc00017f250 sp=0xc00017f1c0 pc=0x4086d8d
syscall.forkExec({0xc0002a0cf9, 0x7}, {0xc00028e4e0, 0x6, 0x6}, 0xc00017f4c8)
        /usr/local/opt/go/libexec/src/syscall/exec_unix.go:210 +0x58f fp=0xc00017f3e8 sp=0xc00017f250 pc=0x4087e0f
syscall.StartProcess(...)
github.com/skycoin/skywire/cmd/skywire-visor/commands.init()                                                                                                                                                     [400/4229]
        /Users/alex/workspace/skycoin/skywire/cmd/skywire-visor/commands/root.go:36 +0x72 fp=0xc00017fd10 sp=0xc00017fcd8 pc=0x4ba3f32
runtime.doInit(0x59e08a0)
        /usr/local/opt/go/libexec/src/runtime/proc.go:6498 +0x123 fp=0xc00017fe48 sp=0xc00017fd10 pc=0x4049663
runtime.doInit(0x59d34c0)
        /usr/local/opt/go/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc00017ff80 sp=0xc00017fe48 pc=0x40495b1
runtime.main()
        /usr/local/opt/go/libexec/src/runtime/proc.go:238 +0x1e6 fp=0xc00017ffe0 sp=0xc00017ff80 pc=0x403bf86
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00017ffe8 sp=0xc00017ffe0 pc=0x406f2a1

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:350 fp=0xc00017f128 sp=0xc00017f120 pc=0x406d060
runtime.libcCall(0x18, 0x5b75720)
        /usr/local/opt/go/libexec/src/runtime/sys_libc.go:49 +0x66 fp=0xc00017f158 sp=0xc00017f128 pc=0x405aea6
syscall.rawSyscall(0x40929e0, 0x0, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/runtime/sys_darwin.go:77 +0x47 fp=0xc00017f178 sp=0xc00017f158 pc=0x406be47
syscall.rawSyscall(0x4071fc5, 0x0, 0x0, 0x1)
        <autogenerated>:1 +0x26 fp=0xc00017f1c0 sp=0xc00017f178 pc=0x40729c6
syscall.forkAndExecInChild(0xc0002a0d38, {0xc00029a2c0, 0x7, 0x1}, {0xc0002af0e0, 0x13, 0x0}, 0x0, 0x0, 0xc00017f4c8, ...)
        /usr/local/opt/go/libexec/src/syscall/exec_libc2.go:80 +0xed fp=0xc00017f250 sp=0xc00017f1c0 pc=0x4086d8d
syscall.forkExec({0xc0002a0cf9, 0x7}, {0xc00028e4e0, 0x6, 0x6}, 0xc00017f4c8)
        /usr/local/opt/go/libexec/src/syscall/exec_unix.go:210 +0x58f fp=0xc00017f3e8 sp=0xc00017f250 pc=0x4087e0f
syscall.StartProcess(...)
        /usr/local/opt/go/libexec/src/syscall/exec_unix.go:256
os.startProcess({0xc0002a0cf9, 0x7}, {0xc00028e4e0, 0x6, 0x6}, 0xc00017f758)
        /usr/local/opt/go/libexec/src/os/exec_posix.go:55 +0x526 fp=0xc00017f520 sp=0xc00017f3e8 pc=0x40cd986
os.StartProcess({0xc0002a0cf9, 0x7}, {0xc00028e4e0, 0x6, 0x6}, 0x2)
        /usr/local/opt/go/libexec/src/os/exec.go:109 +0x7a fp=0xc00017f580 sp=0xc00017f520 pc=0x40cce1a
os/exec.(*Cmd).Start(0xc0002d42c0)
        /usr/local/opt/go/libexec/src/os/exec/exec.go:422 +0x9d4 fp=0xc00017f7b0 sp=0xc00017f580 pc=0x4636174
github.com/shirou/gopsutil/v3/internal/common.Invoke.CommandWithContext({}, {0x5487c90, 0xc0000360d8}, {0xc0002a0cf9, 0x7}, {0xc0002a64b0, 0x5, 0x5})
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/internal/common/common.go:53 +0x1cc fp=0xc00017f838 sp=0xc00017f7b0 pc=0x463f3ec
github.com/shirou/gopsutil/v3/internal/common.(*Invoke).CommandWithContext(0x65c7960, {0x5487c90, 0xc0000360d8}, {0xc0002a0cf9, 0x7}, {0xc0002a64b0, 0x5, 0x5})
        <autogenerated>:1 +0xaf fp=0xc00017f8a8 sp=0xc00017f838 pc=0x463fc4f
github.com/shirou/gopsutil/v3/process.callPsWithContext({0x5487c90, 0xc0000360d8}, {0x4d5f25d, 0x5}, 0xb1ec, 0x0, 0x0)
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process_darwin.go:450 +0x698 fp=0xc00017fa08 sp=0xc00017f8a8 pc=0x4646f18
github.com/shirou/gopsutil/v3/process.(*Process).createTimeWithContext(0xc0002a4820, {0x5487c90, 0xc0000360d8})
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process_darwin.go:127 +0x8b fp=0xc00017faf0 sp=0xc00017fa08 pc=0x464646b
github.com/shirou/gopsutil/v3/process.(*Process).CreateTimeWithContext(0xc0002a4820, {0x5487c90, 0xc0000360d8})
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process.go:287 +0x9d fp=0xc00017fb40 sp=0xc00017faf0 pc=0x46461bd
github.com/shirou/gopsutil/v3/process.NewProcessWithContext({0x5487c90, 0xc0000360d8}, 0xb1ec)
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process.go:195 +0x125 fp=0xc00017fba0 sp=0xc00017fb40 pc=0x4646065
github.com/shirou/gopsutil/v3/process.NewProcess(...)
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process.go:179
github.com/skycoin/skywire/pkg/restart.ppidByPid(0xb1ec)
        /Users/alex/workspace/skycoin/skywire/pkg/restart/restart.go:228 +0x4c fp=0xc00017fbd8 sp=0xc00017fba0 pc=0x464968c
github.com/skycoin/skywire/pkg/restart.CaptureContext()
        /Users/alex/workspace/skycoin/skywire/pkg/restart/restart.go:68 +0x36f fp=0xc00017fcd8 sp=0xc00017fbd8 pc=0x4647f0f
        /usr/local/opt/go/libexec/src/syscall/exec_unix.go:256                                                                                                                                                   [375/4229]
os.startProcess({0xc0002a0cf9, 0x7}, {0xc00028e4e0, 0x6, 0x6}, 0xc00017f758)
        /usr/local/opt/go/libexec/src/os/exec_posix.go:55 +0x526 fp=0xc00017f520 sp=0xc00017f3e8 pc=0x40cd986
os.StartProcess({0xc0002a0cf9, 0x7}, {0xc00028e4e0, 0x6, 0x6}, 0x2)
        /usr/local/opt/go/libexec/src/os/exec.go:109 +0x7a fp=0xc00017f580 sp=0xc00017f520 pc=0x40cce1a
os/exec.(*Cmd).Start(0xc0002d42c0)
        /usr/local/opt/go/libexec/src/os/exec/exec.go:422 +0x9d4 fp=0xc00017f7b0 sp=0xc00017f580 pc=0x4636174
github.com/shirou/gopsutil/v3/internal/common.Invoke.CommandWithContext({}, {0x5487c90, 0xc0000360d8}, {0xc0002a0cf9, 0x7}, {0xc0002a64b0, 0x5, 0x5})
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/internal/common/common.go:53 +0x1cc fp=0xc00017f838 sp=0xc00017f7b0 pc=0x463f3ec
github.com/shirou/gopsutil/v3/internal/common.(*Invoke).CommandWithContext(0x65c7960, {0x5487c90, 0xc0000360d8}, {0xc0002a0cf9, 0x7}, {0xc0002a64b0, 0x5, 0x5})
        <autogenerated>:1 +0xaf fp=0xc00017f8a8 sp=0xc00017f838 pc=0x463fc4f
github.com/shirou/gopsutil/v3/process.callPsWithContext({0x5487c90, 0xc0000360d8}, {0x4d5f25d, 0x5}, 0xb1ec, 0x0, 0x0)
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process_darwin.go:450 +0x698 fp=0xc00017fa08 sp=0xc00017f8a8 pc=0x4646f18
github.com/shirou/gopsutil/v3/process.(*Process).createTimeWithContext(0xc0002a4820, {0x5487c90, 0xc0000360d8})
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process_darwin.go:127 +0x8b fp=0xc00017faf0 sp=0xc00017fa08 pc=0x464646b
github.com/shirou/gopsutil/v3/process.(*Process).CreateTimeWithContext(0xc0002a4820, {0x5487c90, 0xc0000360d8})
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process.go:287 +0x9d fp=0xc00017fb40 sp=0xc00017faf0 pc=0x46461bd
github.com/shirou/gopsutil/v3/process.NewProcessWithContext({0x5487c90, 0xc0000360d8}, 0xb1ec)
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process.go:195 +0x125 fp=0xc00017fba0 sp=0xc00017fb40 pc=0x4646065
github.com/shirou/gopsutil/v3/process.NewProcess(...)
        /Users/alex/workspace/skycoin/skywire/vendor/github.com/shirou/gopsutil/v3/process/process.go:179
github.com/skycoin/skywire/pkg/restart.ppidByPid(0xb1ec)
        /Users/alex/workspace/skycoin/skywire/pkg/restart/restart.go:228 +0x4c fp=0xc00017fbd8 sp=0xc00017fba0 pc=0x464968c
github.com/skycoin/skywire/pkg/restart.CaptureContext()
        /Users/alex/workspace/skycoin/skywire/pkg/restart/restart.go:68 +0x36f fp=0xc00017fcd8 sp=0xc00017fbd8 pc=0x4647f0f
github.com/skycoin/skywire/cmd/skywire-visor/commands.init()
        /Users/alex/workspace/skycoin/skywire/cmd/skywire-visor/commands/root.go:36 +0x72 fp=0xc00017fd10 sp=0xc00017fcd8 pc=0x4ba3f32
runtime.doInit(0x59e08a0)
        /usr/local/opt/go/libexec/src/runtime/proc.go:6498 +0x123 fp=0xc00017fe48 sp=0xc00017fd10 pc=0x4049663
runtime.doInit(0x59d34c0)
        /usr/local/opt/go/libexec/src/runtime/proc.go:6475 +0x71 fp=0xc00017ff80 sp=0xc00017fe48 pc=0x40495b1
runtime.main()
        /usr/local/opt/go/libexec/src/runtime/proc.go:238 +0x1e6 fp=0xc00017ffe0 sp=0xc00017ff80 pc=0x403bf86
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00017ffe8 sp=0xc00017ffe0 pc=0x406f2a1

rax    0x0
rbx    0x147a0600
rcx    0x7ff7bfefef78
rdx    0x0
rdi    0x303
rsi    0x6
rbp    0x7ff7bfefefa0
rsp    0x7ff7bfefef78
r8     0x0
r9     0x0
r10    0x0
r11    0x246
r12    0x303
r13    0x50
r14    0x6
r15    0x16
rip    0x7ff816994112
rflags 0x246
cs     0x7
fs     0x0
gs     0x0

```

**Environment information:**

- OS: MacOS

**Comment by mrpalide** [comment]
No race condition detected on current develop commit (#0d15c2a) with MacOS (Monterey/M1).
