### ISSUE TITLE
Negative WaitGroup counter in SetDetailedStatus 

### ISSUE THREAD

**Issue by ersonp** [skycoin/skywire#1370]
**Describe the bug**
This happens during `e2e-test`
```
panic: sync: negative WaitGroup counter

goroutine 435 [running]:
sync.(*WaitGroup).Add(0x0, 0x0)
        /usr/local/go/src/sync/waitgroup.go:74 +0x105
sync.(*WaitGroup).Done(...)
        /usr/local/go/src/sync/waitgroup.go:99
github.com/skycoin/skywire/pkg/app/appserver.(*Proc).SetDetailedStatus(0xc000239d40, {0xc0018a21c8, 0x7})
        /skywire/pkg/app/appserver/proc.go:337 +0xc5
github.com/skycoin/skywire/pkg/app/appserver.(*RPCIngressGateway).SetDetailedStatus(0xc00006a540, 0xc000345720, 0x1)
        /skywire/pkg/app/appserver/rpc_ingress_gateway.go:82 +0x119
reflect.Value.call({0xc000399500, 0xc0002165d0, 0x13}, {0xb4fb83, 0x4}, {0xc000857ef8, 0x3, 0x3})
        /usr/local/go/src/reflect/value.go:543 +0x814
reflect.Value.Call({0xc000399500, 0xc0002165d0, 0x0}, {0xc00069fef8, 0x3, 0x3})
        /usr/local/go/src/reflect/value.go:339 +0xc5
net/rpc.(*service).call(0xc0004b5000, 0x0, 0x0, 0xc0002138b0, 0xc0001aa580, 0x0, {0xa5ab80, 0xc000345720, 0x0}, {0xa5afc0, ...}, ...)
        /usr/local/go/src/net/rpc/server.go:377 +0x239
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:474 +0x405
```

**Comment by 0pcom** [comment]
fixed in #1372
