### ISSUE TITLE
panic on shutdown v1.3.9

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1594]
```
^C[2023-05-29T07:47:22.375523638-05:00] INFO []: Closing with received signal. signal=interrupt
[2023-05-29T07:47:22.375694903-05:00] DEBUG [transport_setup]: Dmsg client stopped serving. error="dmsg error 200 - local entity closed"
[2023-05-29T07:47:22.37576465-05:00] INFO [visor:shutdown]: Begin shutdown.
[2023-05-29T07:47:22.375857857-05:00] DEBUG [17/17] [visor:shutdown:hypervisor]: Shutting down module...
[2023-05-29T07:47:22.37601028-05:00] DEBUG [17/17] [visor:shutdown:hypervisor]: Module stopped cleanly. elapsed=157.129µs
[2023-05-29T07:47:22.376054569-05:00] DEBUG [16/17] [visor:shutdown:skywire_ping]: Shutting down module...
[2023-05-29T07:47:22.37611442-05:00] DEBUG [16/17] [visor:shutdown:skywire_ping]: Module stopped cleanly. elapsed=64.732µs
[2023-05-29T07:47:22.376146918-05:00] DEBUG [15/17] [visor:shutdown:sky_forwarding]: Shutting down module...
[2023-05-29T07:47:22.376189741-05:00] DEBUG [15/17] [visor:shutdown:sky_forwarding]: Module stopped cleanly. elapsed=46.056µs
[2023-05-29T07:47:22.376220779-05:00] DEBUG [14/17] [visor:shutdown:dmsgctrl]: Shutting down module...
[2023-05-29T07:47:22.37625577-05:00] DEBUG [14/17] [visor:shutdown:dmsgctrl]: Module stopped cleanly. elapsed=38.585µs
[2023-05-29T07:47:22.376274937-05:00] DEBUG [13/17] [visor:shutdown:launcher.proc_manager]: Shutting down module...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8022d6]

goroutine 7219 [running]:
go.etcd.io/bbolt.(*Bucket).Put(0xc0001e01d8?, {0xc00003ce70?, 0x73?, 0x8?}, {0xc000766100?, 0x7fbdf1ca8348?, 0xc00043e1b8?})
	go.etcd.io/bbolt@v1.3.6/bucket.go:281 +0x36
github.com/skycoin/skywire/pkg/app/appcommon.(*bBoltLogStore).Fire.func2(0x50d1c5?)
	github.com/skycoin/skywire/pkg/app/appcommon/log_store.go:221 +0xaf
go.etcd.io/bbolt.(*DB).Update(0xc000766081?, 0xc004599218)
	go.etcd.io/bbolt@v1.3.6/db.go:741 +0x82
github.com/skycoin/skywire/pkg/app/appcommon.(*bBoltLogStore).Fire(0xc00012e900, 0xc004491318?)
	github.com/skycoin/skywire/pkg/app/appcommon/log_store.go:219 +0x22e
github.com/sirupsen/logrus.LevelHooks.Fire(0xc004491348?, 0x4491318?, 0x6?)
	github.com/sirupsen/logrus@v1.8.1/hooks.go:28 +0x7a
github.com/sirupsen/logrus.(*Entry).fireHooks(0xc000244af0)
	github.com/sirupsen/logrus@v1.8.1/entry.go:272 +0x1f0
github.com/sirupsen/logrus.(*Entry).log(0xc0001fa1c0, 0x4, {0xc00076e138, 0x16})
	github.com/sirupsen/logrus@v1.8.1/entry.go:241 +0x38c
github.com/sirupsen/logrus.(*Entry).Log(0xc0001fa1c0, 0x4, {0xc0044915e8?, 0x2?, 0x2?})
	github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Entry).Logf(0xc0001fa1c0, 0x4, {0xe66067?, 0x40d4e7?}, {0xc00007c600?, 0xd12e00?, 0xd13001?})
	github.com/sirupsen/logrus@v1.8.1/entry.go:338 +0x85
github.com/sirupsen/logrus.(*Entry).Infof(0xc00061bac0?, {0xe66067?, 0x0?}, {0xc00007c600?, 0x0?, 0x0?})
	github.com/sirupsen/logrus@v1.8.1/entry.go:351 +0x37
github.com/skycoin/skywire/pkg/app/appserver.(*Proc).SetDetailedStatus(0xc0004a8500, {0xc00061bac0, 0x7})
	github.com/skycoin/skywire/pkg/app/appserver/proc.go:360 +0x263
github.com/skycoin/skywire/pkg/app/appserver.(*RPCIngressGateway).SetDetailedStatus(0xc00070a180, 0xc0006f62c0, 0x1?)
	github.com/skycoin/skywire/pkg/app/appserver/rpc_ingress_gateway.go:83 +0xf9
reflect.Value.call({0xc000534a20?, 0xc0000141e8?, 0x13?}, {0xe56dd6, 0x4}, {0xc000598ef8, 0x3, 0x3?})
	reflect/value.go:586 +0xb0b
reflect.Value.Call({0xc000534a20?, 0xc0000141e8?, 0xc00050b760?}, {0xc00050b6f8?, 0xc00050b6f8?, 0x407f85?})
	reflect/value.go:370 +0xbc
net/rpc.(*service).call(0xc0005a01c0, 0x0?, 0x0?, 0xc00048e230, 0xc000690500, 0x1a6e0b0?, {0xcfb180?, 0xc0006f62c0?, 0xc000410e60?}, {0xcfb680, ...}, ...)
	net/rpc/server.go:382 +0x226
created by net/rpc.(*Server).ServeCodec
	net/rpc/server.go:479 +0x3fe

```

**Comment by 0pcom** [comment]
this does not affect anything currently because the systemd service will restart the visor regardless of it's exit status.

**Comment by mrpalide** [comment]
Cannot reproduce it on Mac/Linux with v1.3.9 in all scenarios!
- shutting down with all running app
- shutting down without any running app
- shutting down during starting an app
- ...

btw, based on logs, it happened when proc_manager module trying shutdown, and in inner libs, a nil pointer appear in calling tx of bbolt bucket, and is not meaning full!

![image](https://github.com/skycoin/skywire/assets/79150699/c9243b55-7c08-420c-95fd-f2ff1ec8c2eb)


So will remain open this issue til appears again before next two release. If not, then will close it.
