### ISSUE TITLE
panic on `skywire-cli log` with 1.3.15

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire#1709]
![image](https://github.com/skycoin/skywire/assets/36607567/e683529f-6862-4fff-8c48-111b84c3353c)
```
[0pcom@host rewards]$ skywire-cli log -s $(tail -n1 survey-wl.conf)
[2023-12-27T15:36:43.998521874-06:00] DEBUG [log-collecting]: Successfully  called uptime service and received answer []
[2023-12-27T15:36:44.019480454-06:00] DEBUG disc.NewHTTP [log-collecting]: Created HTTP client. addr="http://dmsgd.skywire.skycoin.com"
[2023-12-27T15:36:44.019569427-06:00] INFO [log-collecting]: Connecting to dmsg network... dmsg_disc="http://dmsgd.skywire.skycoin.com" public_key="03714c8bdaee0fb48f47babbc47c33e1880752b6620317c9d56b30f3b0ff58a9c3"
[2023-12-27T15:36:44.019686167-06:00] DEBUG [dmsg_client]: Discovering dmsg servers...
[2023-12-27T15:36:44.491543188-06:00] DEBUG [dmsg_client]: Dialing session... remote_pk=0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7
[2023-12-27T15:36:44.985985308-06:00] DEBUG [dmsg_client]: Serving session. remote_pk=0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7
[2023-12-27T15:36:44.986043258-06:00] INFO [log-collecting]: Dmsg network ready.
[2023-12-27T15:36:45.670495664-06:00] DEBUG [dmsg_client]: Dialing session... remote_pk=03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4
[2023-12-27T15:36:46.168728722-06:00] DEBUG [dmsg_client]: Updating entry. entry=	version: 0.0.1
	sequence: 0
	registered at: 1703713004747748122
	static public key: 03714c8bdaee0fb48f47babbc47c33e1880752b6620317c9d56b30f3b0ff58a9c3
	signature: c50bc0f42b239b1abff7cc658df4b49ddaba24ed0f611586bdc4e5b26ea982d55f6777c6362b566d871ad073f2a672f22615e11a01945e27af000d9b80dd85de00
	entry is registered as client. Related info: 
		delegated servers: 
			0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7
			03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4


[2023-12-27T15:36:46.399727098-06:00] DEBUG [dmsg_client]: Serving session. remote_pk=03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4
[2023-12-27T15:36:46.863168442-06:00] DEBUG [dmsg_client]: Dialing session... remote_pk=0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13
[2023-12-27T15:36:47.361917861-06:00] DEBUG [dmsg_client]: Updating entry. entry=	version: 0.0.1
	sequence: 1
	registered at: 1703713006168904719
	static public key: 03714c8bdaee0fb48f47babbc47c33e1880752b6620317c9d56b30f3b0ff58a9c3
	signature: 8e977ee3e9f89b4a7b107216bf29132f288b855d88bb002f1e4b9e80a880dcc7714195ab08b4839efb595b65641872f5c06de1f971382a4b1a0b6da1aa2a3ea900
	entry is registered as client. Related info: 
		delegated servers: 
			0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7
			03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4
			0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13


[2023-12-27T15:36:47.593913145-06:00] DEBUG [dmsg_client]: Serving session. remote_pk=0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13
[2023-12-27T15:36:48.043249656-06:00] DEBUG [dmsg_client]: Dialing session... remote_pk=0228af3fd99c8d86a882495c8e0202bdd4da78c69e013065d8634286dd4a0ac098
[2023-12-27T15:36:48.763839747-06:00] DEBUG [dmsg_client]: Updating entry. entry=	version: 0.0.1
	sequence: 2
	registered at: 1703713007362006726
	static public key: 03714c8bdaee0fb48f47babbc47c33e1880752b6620317c9d56b30f3b0ff58a9c3
	signature: 716bd874ed61c2b24ecf4fa9b2feb6b3840e0f31d521d47d4d4a64e9353fe46479ea3e88ed713256e4a08c7b7caea6dd5456eabc110eaa974f7fb3c968535ffe00
	entry is registered as client. Related info: 
		delegated servers: 
			0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7
			03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4
			0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13
			0228af3fd99c8d86a882495c8e0202bdd4da78c69e013065d8634286dd4a0ac098


[2023-12-27T15:36:48.996416522-06:00] DEBUG [dmsg_client]: Serving session. remote_pk=0228af3fd99c8d86a882495c8e0202bdd4da78c69e013065d8634286dd4a0ac098
[2023-12-27T15:36:49.447623305-06:00] DEBUG [dmsg_client]: Dialing session... remote_pk=030c83534af1041aee60c2f124b682a9d60c6421876db7c67fc83a73c5effdbd96
[2023-12-27T15:36:50.63005492-06:00] DEBUG [dmsg_client]: Updating entry. entry=	version: 0.0.1
	sequence: 3
	registered at: 1703713008763911124
	static public key: 03714c8bdaee0fb48f47babbc47c33e1880752b6620317c9d56b30f3b0ff58a9c3
	signature: 89c2c0ec1e0785f209c24165f74ca56cb7e7f3d753c1ee71be661e7e28957ce022a0381b04e68eef98f3a29b3f6d4c6e55d0e69401147652077c59fa7b17a8db00
	entry is registered as client. Related info: 
		delegated servers: 
			03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4
			0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13
			0228af3fd99c8d86a882495c8e0202bdd4da78c69e013065d8634286dd4a0ac098
			030c83534af1041aee60c2f124b682a9d60c6421876db7c67fc83a73c5effdbd96
			0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7


[2023-12-27T15:36:50.865372619-06:00] DEBUG [dmsg_client]: Serving session. remote_pk=030c83534af1041aee60c2f124b682a9d60c6421876db7c67fc83a73c5effdbd96
[2023-12-27T15:36:51.328779285-06:00] DEBUG [dmsg_client]: Dialing session... remote_pk=02a49bc0aa1b5b78f638e9189be4ed095bac5d6839c828465a8350f80ac07629c0
[2023-12-27T15:36:51.831539857-06:00] DEBUG [dmsg_client]: Updating entry. entry=	version: 0.0.1
	sequence: 4
	registered at: 1703713010630158871
	static public key: 03714c8bdaee0fb48f47babbc47c33e1880752b6620317c9d56b30f3b0ff58a9c3
	signature: 76135bacb004ba00f0736a6e17e46bf65c4c9b9132d743d1eac9ceebe44f0b0b6097dc3762010508e79e4c44730f6fcff66568855d34db5e04eb38d93a61210c01
	entry is registered as client. Related info: 
		delegated servers: 
			0228af3fd99c8d86a882495c8e0202bdd4da78c69e013065d8634286dd4a0ac098
			030c83534af1041aee60c2f124b682a9d60c6421876db7c67fc83a73c5effdbd96
			02a49bc0aa1b5b78f638e9189be4ed095bac5d6839c828465a8350f80ac07629c0
			0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7
			03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4
			0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13


[2023-12-27T15:36:52.068456698-06:00] DEBUG [dmsg_client]: Serving session. remote_pk=02a49bc0aa1b5b78f638e9189be4ed095bac5d6839c828465a8350f80ac07629c0
[2023-12-27T15:36:52.526672846-06:00] DEBUG [dmsg_client]: Dialing session... remote_pk=03d5b55d1133b26485c664cf8b95cff6746d1e321c34e48c9fed293eff0d6d49e5
[2023-12-27T15:36:53.238010969-06:00] DEBUG [dmsg_client]: Updating entry. entry=	version: 0.0.1
	sequence: 5
	registered at: 1703713011831629698
	static public key: 03714c8bdaee0fb48f47babbc47c33e1880752b6620317c9d56b30f3b0ff58a9c3
	signature: fcbe172e6e40ddc396896f1dd92c9debe0872307a7585458d69bef33a433535d065c2088f1c44a385aef414fe5ded2005bc78b2f9d5f173047cdd2401b4ad72701
	entry is registered as client. Related info: 
		delegated servers: 
			02a49bc0aa1b5b78f638e9189be4ed095bac5d6839c828465a8350f80ac07629c0
			03d5b55d1133b26485c664cf8b95cff6746d1e321c34e48c9fed293eff0d6d49e5
			0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7
			03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4
			0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13
			0228af3fd99c8d86a882495c8e0202bdd4da78c69e013065d8634286dd4a0ac098
			030c83534af1041aee60c2f124b682a9d60c6421876db7c67fc83a73c5effdbd96


[2023-12-27T15:36:53.469003442-06:00] DEBUG [dmsg_client]: Serving session. remote_pk=03d5b55d1133b26485c664cf8b95cff6746d1e321c34e48c9fed293eff0d6d49e5
[2023-12-27T15:36:53.936191695-06:00] DEBUG [dmsg_client]: Dialing session... remote_pk=0281a102c82820e811368c8d028cf11b1a985043b726b1bcdb8fce89b27384b2cb
[2023-12-27T15:36:54.44606508-06:00] DEBUG [dmsg_client]: Updating entry. entry=	version: 0.0.1
	sequence: 6
	registered at: 1703713013238153640
	static public key: 03714c8bdaee0fb48f47babbc47c33e1880752b6620317c9d56b30f3b0ff58a9c3
	signature: f3806f92ea9adae80a48834e577fc8e8724c39e8c35c633121743ea00736335a583195394e86653ce4f9f1676d1a3e44af83c0c0df045175fa362a6ba024a93501
	entry is registered as client. Related info: 
		delegated servers: 
			03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4
			0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13
			0228af3fd99c8d86a882495c8e0202bdd4da78c69e013065d8634286dd4a0ac098
			030c83534af1041aee60c2f124b682a9d60c6421876db7c67fc83a73c5effdbd96
			02a49bc0aa1b5b78f638e9189be4ed095bac5d6839c828465a8350f80ac07629c0
			03d5b55d1133b26485c664cf8b95cff6746d1e321c34e48c9fed293eff0d6d49e5
			0281a102c82820e811368c8d028cf11b1a985043b726b1bcdb8fce89b27384b2cb
			0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7


[2023-12-27T15:36:54.683409869-06:00] DEBUG [dmsg_client]: Serving session. remote_pk=0281a102c82820e811368c8d028cf11b1a985043b726b1bcdb8fce89b27384b2cb
[2023-12-27T15:36:55.13880422-06:00] DEBUG [dmsg_client]: Dialing session... remote_pk=02a2d4c346dabd165fd555dfdba4a7f4d18786fe7e055e562397cd5102bdd7f8dd
[2023-12-27T15:36:55.640391287-06:00] DEBUG [dmsg_client]: Updating entry. entry=	version: 0.0.1
	sequence: 7
	registered at: 1703713014446166197
	static public key: 03714c8bdaee0fb48f47babbc47c33e1880752b6620317c9d56b30f3b0ff58a9c3
	signature: 89c8da93ae1b0f857c3b766a6b1ae5a5f47cf08ae134a94b7af90e80aa92fdf8192d4dd648e6b428bb20678b27d00ee56a0fa4faca49d9f22725166ec5e3599601
	entry is registered as client. Related info: 
		delegated servers: 
			03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4
			0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13
			02a49bc0aa1b5b78f638e9189be4ed095bac5d6839c828465a8350f80ac07629c0
			0281a102c82820e811368c8d028cf11b1a985043b726b1bcdb8fce89b27384b2cb
			02a2d4c346dabd165fd555dfdba4a7f4d18786fe7e055e562397cd5102bdd7f8dd
			0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7
			0228af3fd99c8d86a882495c8e0202bdd4da78c69e013065d8634286dd4a0ac098
			030c83534af1041aee60c2f124b682a9d60c6421876db7c67fc83a73c5effdbd96
			03d5b55d1133b26485c664cf8b95cff6746d1e321c34e48c9fed293eff0d6d49e5


[2023-12-27T15:36:55.873471127-06:00] WARN [log-collecting]: The version v1.3.14 for visor 03ecd99b9658c88ec456ac58925ba258984a5d696303e6fa79cde3a3b46550669e does not satisfy our minimum version condition
[2023-12-27T15:36:55.873533832-06:00] WARN [log-collecting]: The version v1.3.13 for visor 03ed10f99432e37512812b6576d8df1770bb993c85441140c48ad846d663d4017e does not satisfy our minimum version condition
[2023-12-27T15:36:55.873580235-06:00] WARN [log-collecting]: The version v1.3.13 for visor 03e0f7cdb788c94e0c37f06fc5cbe4dd6a5a837039bab79197839a93f0eae06522 does not satisfy our minimum version condition
[2023-12-27T15:36:55.873490592-06:00] DEBUG [dmsg_client]: Serving session. remote_pk=02a2d4c346dabd165fd555dfdba4a7f4d18786fe7e055e562397cd5102bdd7f8dd
[2023-12-27T15:36:55.873615383-06:00] WARN [log-collecting]: The version v1.3.13 for visor 02278ca4971ae1e63a47a5a7b290e21f22f8e523d2da6f88f8965731ca2fe2f274 does not satisfy our minimum version condition
[2023-12-27T15:36:55.873770347-06:00] WARN [log-collecting]: The version v1.3.13 for visor 02a6d2db513db03a8eeaf3f4c560b340cf1d4209599d034b7127e66324745eb341 does not satisfy our minimum version condition
[2023-12-27T15:36:55.873813009-06:00] WARN [log-collecting]: The version v1.3.11 for visor 03d07ae055ca72b6c0632ce3461708416340e6a02d3d4969f1ad1b6fe2f6136b65 does not satisfy our minimum version condition
[2023-12-27T15:36:55.873902597-06:00] WARN [log-collecting]: The version v1.3.6 for visor 0230bd0ebf494619b88e5bda1592ca683d52c4ceef1dcef3c355ae96ad593bafc1 does not satisfy our minimum version condition
[2023-12-27T15:36:55.874064823-06:00] DEBUG [dmsg_client]: Stopped accepting streams. error="session shutdown" session=0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7
[2023-12-27T15:36:55.874097239-06:00] DEBUG [dmsg_client]: Stopped serving client!
[2023-12-27T15:36:55.874103058-06:00] DEBUG [dmsg_client]: Session closed. error=<nil>
[2023-12-27T15:36:55.874191794-06:00] DEBUG [dmsg_client]: Stopped accepting streams. error="session shutdown" session=0228af3fd99c8d86a882495c8e0202bdd4da78c69e013065d8634286dd4a0ac098
[2023-12-27T15:36:55.874217973-06:00] DEBUG [dmsg_client]: Session closed. error=<nil>
[2023-12-27T15:36:55.874292084-06:00] DEBUG [dmsg_client]: Stopped accepting streams. error="session shutdown" session=030c83534af1041aee60c2f124b682a9d60c6421876db7c67fc83a73c5effdbd96
[2023-12-27T15:36:55.87440358-06:00] DEBUG [dmsg_client]: Session closed. error=<nil>
[2023-12-27T15:36:55.874474328-06:00] DEBUG [dmsg_client]: Stopped accepting streams. error="session shutdown" session=03d5b55d1133b26485c664cf8b95cff6746d1e321c34e48c9fed293eff0d6d49e5
[2023-12-27T15:36:55.874521568-06:00] DEBUG [dmsg_client]: Session closed. error=<nil>
[2023-12-27T15:36:55.874567094-06:00] DEBUG [dmsg_client]: Stopped accepting streams. error="session shutdown" session=02a2d4c346dabd165fd555dfdba4a7f4d18786fe7e055e562397cd5102bdd7f8dd
[2023-12-27T15:36:55.874658421-06:00] DEBUG [dmsg_client]: Session closed. error=<nil>
[2023-12-27T15:36:55.874730126-06:00] DEBUG [dmsg_client]: Stopped accepting streams. error="session shutdown" session=03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4
[2023-12-27T15:36:55.874779466-06:00] DEBUG [dmsg_client]: Session closed. error=<nil>
[2023-12-27T15:36:55.874830467-06:00] DEBUG [dmsg_client]: Stopped accepting streams. error="session shutdown" session=0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13
[2023-12-27T15:36:55.874914515-06:00] DEBUG [dmsg_client]: Session closed. error=<nil>
[2023-12-27T15:36:55.87496188-06:00] DEBUG [dmsg_client]: Stopped accepting streams. error="session shutdown" session=02a49bc0aa1b5b78f638e9189be4ed095bac5d6839c828465a8350f80ac07629c0
[2023-12-27T15:36:55.875064864-06:00] DEBUG [dmsg_client]: Session closed. error=<nil>
[2023-12-27T15:36:55.875113439-06:00] DEBUG [dmsg_client]: Stopped accepting streams. error="session shutdown" session=0281a102c82820e811368c8d028cf11b1a985043b726b1bcdb8fce89b27384b2cb
[2023-12-27T15:36:55.87519598-06:00] DEBUG [dmsg_client]: Session closed. error=<nil>
[2023-12-27T15:36:55.875232818-06:00] DEBUG [dmsg_client]: All sessions closed.
[2023-12-27T15:36:56.348422288-06:00] DEBUG [dmsg_client]: Deleting entry. entry=	version: 0.0.1
	sequence: 8
	registered at: 1703713015640555524
	static public key: 03714c8bdaee0fb48f47babbc47c33e1880752b6620317c9d56b30f3b0ff58a9c3
	signature: 770a31f09a7865528d5608c96124db760ae07829ebfa907c47933e63a4ef30ef1253bc621d4deca3dce33e3fa6c332da655a63e52c4a2c379e09986300736ada01
	entry is registered as client. Related info: 
		delegated servers: 
			03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4
			0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13
			02a49bc0aa1b5b78f638e9189be4ed095bac5d6839c828465a8350f80ac07629c0
			0281a102c82820e811368c8d028cf11b1a985043b726b1bcdb8fce89b27384b2cb
			02a2d4c346dabd165fd555dfdba4a7f4d18786fe7e055e562397cd5102bdd7f8dd
			0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7
			0228af3fd99c8d86a882495c8e0202bdd4da78c69e013065d8634286dd4a0ac098
			030c83534af1041aee60c2f124b682a9d60c6421876db7c67fc83a73c5effdbd96
			03d5b55d1133b26485c664cf8b95cff6746d1e321c34e48c9fed293eff0d6d49e5


[2023-12-27T15:36:56.583915992-06:00] DEBUG [dmsg_client]: Dialing session... remote_pk=0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7
[2023-12-27T15:36:56.586389008-06:00] DEBUG [dmsg_client]: Entry Deleted successfully.
[2023-12-27T15:36:56.586426122-06:00] INFO [log-collecting]: Disconnected from dmsg network. error=<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xdec7f3]

goroutine 1 [running, locked to thread]:
github.com/hashicorp/go-version.(*Version).String(0x0)
	/home/runner/work/skywire/skywire/vendor/github.com/hashicorp/go-version/version.go:369 +0x33
github.com/hashicorp/go-version.(*Version).Compare(0x0, 0xc000584140)
	/home/runner/work/skywire/skywire/vendor/github.com/hashicorp/go-version/version.go:116 +0x25
github.com/hashicorp/go-version.(*Version).LessThan(...)
	/home/runner/work/skywire/skywire/vendor/github.com/hashicorp/go-version/version.go:308
github.com/skycoin/skywire/cmd/skywire-cli/commands/log.glob..func1(0xc00024cb00?, {0x1003b39?, 0x4?, 0x1003b69?})
	/home/runner/work/skywire/skywire/cmd/skywire-cli/commands/log/root.go:172 +0xf13
github.com/spf13/cobra.(*Command).execute(0x1e55420, {0xc000718060, 0x2, 0x2})
	/home/runner/work/skywire/skywire/vendor/github.com/spf13/cobra/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x1e51aa0)
	/home/runner/work/skywire/skywire/vendor/github.com/spf13/cobra/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/skywire/skywire/vendor/github.com/spf13/cobra/command.go:992
github.com/skycoin/skywire/cmd/skywire-cli/commands.Execute()
	/home/runner/work/skywire/skywire/cmd/skywire-cli/commands/root.go:226 +0x67
main.main()
	/home/runner/work/skywire/skywire/cmd/skywire-cli/skywire-cli.go:9 +0xf

```

**Comment by 0pcom** [comment]
fixed in https://github.com/skycoin/skywire/pull/1711
