### ISSUE TITLE
TestVisorSpawnApp does not pass in rare cases

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire#176]
**Describe the bug**
```
[2020-03-02T13:29:39+01:00] INFO [test]: Starting foo.v1.0
[2020-03-02T13:29:39+01:00] INFO [test]: storing app foo pid 10
[2020-03-02T13:29:39+01:00] INFO [test]: Stopping app foo and closing ports
[2020-03-02T13:29:39+01:00] INFO [dmsg_client]: Discovering dmsg servers...
[2020-03-02T13:29:39+01:00] INFO [test]: killing previously ran apps if any...
[2020-03-02T13:29:39+01:00] WARN [dmsg_client]: No entries found. Retrying after 1s...
[2020-03-02T13:29:39+01:00] WARN [pathutil]: Failed to remove file /Users/nkryuchkov/.skycoin/skywire/028a8d548f449511b86589a3a3e0db25d3b6eb0c83ae802029c0a9f6448d923f93/apps-pid.txt251668715 error="remove /Users/nkryuchkov/.skycoin/skywire/028a8d548f449511b86589a3a3e0db25d3b6eb0c83ae802029c0a9f6448d923f93/apps-pid.txt251668715: no such file or directory"
panic: remove /Users/nkryuchkov/.skycoin/skywire/028a8d548f449511b86589a3a3e0db25d3b6eb0c83ae802029c0a9f6448d923f93/apps-pid.txt251668715: no such file or directory

goroutine 26 [running]:
github.com/SkycoinProject/skywire-mainnet/pkg/util/pathutil.AtomicWriteFile(0xc00031c200, 0x72, 0xc0002a4400, 0x7, 0x200)
        /Users/nkryuchkov/GolandProjects/skywire-mainnet/pkg/util/pathutil/homedir.go:68 +0x454
github.com/SkycoinProject/skywire-mainnet/pkg/util/pathutil.AtomicAppendToFile(0xc00031c200, 0x72, 0xc0000b3aa0, 0x7, 0x20)
        /Users/nkryuchkov/GolandProjects/skywire-mainnet/pkg/util/pathutil/homedir.go:79 +0x13f
github.com/SkycoinProject/skywire-mainnet/pkg/visor.(*Visor).persistPID(0xc0002e00f0, 0x18e2f35, 0x3, 0xc00019000a)
        /Users/nkryuchkov/GolandProjects/skywire-mainnet/pkg/visor/visor.go:511 +0x21c
github.com/SkycoinProject/skywire-mainnet/pkg/visor.(*Visor).SpawnApp(0xc0002e00f0, 0xc0000b3fa0, 0xc0002ab800, 0x0, 0x0)
        /Users/nkryuchkov/GolandProjects/skywire-mainnet/pkg/visor/visor.go:498 +0x123c
github.com/SkycoinProject/skywire-mainnet/pkg/visor.(*Visor).StartApp.func1(0xc0002e00f0, 0xc0002ab800, 0x18e2f35, 0x3, 0x18e2d91, 0x3, 0x18e2f35, 0x3, 0xa0000, 0x0, ...)
        /Users/nkryuchkov/GolandProjects/skywire-mainnet/pkg/visor/visor.go:436 +0x6c
created by github.com/SkycoinProject/skywire-mainnet/pkg/visor.(*Visor).StartApp
        /Users/nkryuchkov/GolandProjects/skywire-mainnet/pkg/visor/visor.go:435 +0x2e4
FAIL    github.com/SkycoinProject/skywire-mainnet/pkg/visor     2.317s
FAIL
make: *** [test] Error 1
```

**Steps to Reproduce**

`make check`

**Comment by nkryuchkov** [comment]
Accidentally created a duplicate: https://github.com/SkycoinProject/skywire-mainnet/issues/184. Therefore this should be closed.
