### ISSUE TITLE
Tests depend on production deployment

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#764]
**Describe the bug**
Some of our tests depend on the dmsg Discovery and server working properly in production. If production is unavailable or a network connection is not available, the tests fail.

**Comment by jdknives** [comment]
At least `visor.TestMain` is affected.

**Comment by i-hate-nicknames** [comment]
The [build](https://travis-ci.com/github/skycoin/skywire/builds/225723574#L1809) where it happened 
Goroutines that mention _test.go files in their stack trace:
```
goroutine 1 [chan receive, 4 minutes]:
testing.(*T).Run(0xc0002e0000, 0x124d7f8, 0xc, 0x127ece8, 0x1)
	/home/nvm/local/bin/go/src/testing/testing.go:1240 +0x610
testing.runTests.func1(0xc0002e0000)
	/home/nvm/local/bin/go/src/testing/testing.go:1512 +0xa7
testing.tRunner(0xc0002e0000, 0xc00029bb60)
	/home/nvm/local/bin/go/src/testing/testing.go:1194 +0x203
testing.runTests(0xc000290090, 0x19bc620, 0x4, 0x4, 0xc01f0cc39cafede5, 0x45ec641117, 0x19ca860, 0x11bf840)
	/home/nvm/local/bin/go/src/testing/testing.go:1510 +0x613
testing.(*M).Run(0xc0002a8080, 0x0)
	/home/nvm/local/bin/go/src/testing/testing.go:1418 +0x3b4
github.com/skycoin/skywire/pkg/visor.TestMain(0xc0002a8080)
	/home/nvm/work/sky/skywire/pkg/visor/visor_test.go:39 +0x3db
main.main()
	_testmain.go:119 +0x372
```

```
goroutine 97 [select, 4 minutes]:
github.com/skycoin/skywire/pkg/transport/setup.NewTransportListener(0x1398bd8, 0xc0002304c0, 0xc0004e69a0, 0xc00045e000, 0xc00014a420, 0x0, 0x4, 0xc00040e1c8)
	/home/nvm/work/sky/skywire/pkg/transport/setup/visor.go:32 +0x34b
github.com/skycoin/skywire/pkg/visor.initTransportSetup(0xc00055b760, 0x4)
	/home/nvm/work/sky/skywire/pkg/visor/init.go:226 +0x1b8
github.com/skycoin/skywire/pkg/visor.NewVisor(0xc0004e69a0, 0xc0002b8550, 0xc0004fc000, 0xd413648ce64b1d01)
	/home/nvm/work/sky/skywire/pkg/visor/visor.go:153 +0xc3e
github.com/skycoin/skywire/pkg/visor.TestNewVisor(0xc000361c80)
	/home/nvm/work/sky/skywire/pkg/visor/visor_test.go:87 +0xd9f
testing.tRunner(0xc000361c80, 0x127ece8)
	/home/nvm/local/bin/go/src/testing/testing.go:1194 +0x203
created by testing.(*T).Run
	/home/nvm/local/bin/go/src/testing/testing.go:1239 +0x5d8
```

**Comment by jdknives** [comment]
The `visor_test.go` file does not exist anymore on current `develop` branch. So I will close this ticket.
